name: Run Clippy

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Clippy
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      RUST_BACKTRACE: full
      RUSTC_WRAPPER: sccache
      SCCACHE_CACHE_SIZE: 2G
    steps:
      - uses: actions/checkout@v3
      - name: Setup sccache
        uses: ./.github/actions/setup-sccache

      - name: Run clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          toolchain: stable
          args: --all-targets --all-features -- -D warnings

      - uses: ./.github/actions/post-sccache
