name: Run Fmt

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Rustfmt
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      RUST_BACKTRACE: full
      RUSTC_WRAPPER: sccache
      SCCACHE_CACHE_SIZE: 2G
    steps:
      - uses: actions/checkout@v3
      - name: Setup sccache
        uses: ./.github/actions/setup-sccache

      - name: Run fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          toolchain: stable
          args: --all -- --check

      - uses: ./.github/actions/post-sccache
